# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.


  # This Vagrantfile is specifically for the appmaker application, cloned from https://github.com/mozilla/mozilla-appmaker
  # As of 1/17/14, this is in rough draft, please submit
  # bugs via webmaker :: devops, or email jp@mozillafoundation.org
  config.vm.box = "appmaker"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  #config.vm.box_url = "https://dl.dropboxusercontent.com/u/2273146/appmaker.box"

  # Create forwarded port mappings
  # appmaker apps have the following port assignments/urls
  # which are opened up to your local workstation by the
  # following stanzas

  # Configure elasticsearch port forwards

  config.vm.network :forwarded_port, guest: 27017, host: 27017
  config.vm.network :forwarded_port, guest: 5000, host: 5000

end
